version: '3.6'

# Docker-Compose 单容器使用参考 YAML 配置文件
# 更多配置参数请参考镜像 README.md 文档中说明
services:
  php-fpm:
    image: 'colovu/php-fpm:latest'
    volumes:
      - '/tmp/conf:/srv/conf'
      - '/tmp/data:/srv/data'

